development: &base
  site: book
  use_ssl: true
  rooms:
    - Winterns
  api_key: 9855c889bcde0b4968d921e7848480ab6e0868bc
  nickname: SRK
  fullname: Shah Rukh Khan
  enable_plugins: 
    - xkcd
    - fail
    - excuse
    - lolcats
    - insult
    - image_me
    - say_hello
    - compliment
    - help
    - selenium
    - restart
    - first_world_problems
    - say_whats
    - selleck
    - rolodex
    - clearscreen
    - magic_eight_ball
    - text

production:
  <<: *base
  rooms:
    - BookRenter
    - BookRenter w/ Sounds
