development: &base
  site: book
  use_ssl: true
  rooms:
    - Graphic Design
  api_key: b87b690f016e0240fe1aeedbaf91b6820fb5aa45
  nickname: Al
  fullname: Al the Gator
  enable_plugins: 
    - xkcd
    - fail
    - excuse
    - lolcats
    - image_me
    - insult
    - compliment
    - help
    - deploy
    - selenium
    - restart
    - first_world_problems
    - say_whats
    - selleck
    - rolodex
    - teamcity_simple
    - clearscreen
    - magic_eight_ball
    - performance_alerts

production:
  <<: *base
  rooms:
    - BookRenter
    - BookRenter w/ Sounds