dont_know_responses:
  - "Sorry, busy looking at Facebook right now. I'd try"
  - "Too stressed to think about it from all this distributor integration work Paolo and I are doing. I hate NACS! Try"
  - "Too stressed to think about it from all this distributor integration work Paolo and I are doing. I hate Follett! Try"
  - "Too stressed to think about it from all this distributor integration work Paolo and I are doing. I hate MBS! Try"
  - "Too stressed to think about it from all this distributor integration work Paolo and I are doing. I hate B&T! Try"
  - "If its bad code, I'd blame Philippe. Otherwise try"
  - "I'm not sure. My answer will probably be as bad as Probie's. Try"
  - "Mark seems to have strong opinions on these things. Maybe he knows. Or try"
  - "Pearce probably knows, but is too busy with his record label to be bothered with such things. Try"
  - "Kamy isn't paying attention, but I'd ask him. Or try"
  - "Sorry, i don't understand the Queen's English. I bet Cameron knows the answer. Or try"
  - "You may want to ask Corinne's friend with the website from 1999. Or maybe just try"
  - "I could give a fake answer like Denny. Instead I'll just admit I don't know. Try"
  - "Pearce probably knows, but is loitering by the playground at the moment. Try"
  - "I can't help - Andrew's Shared Should Gem has my whole environment messed up right now. Try"
  - "That sounds designer-y to me. Is this something Harlan knows about? Or try"
  - "That sounds designer-y to me. Is this something Ben D. knows about? Or try"
  - "I'm sure Chris knows, but he's doing DevOps stuff now and can't waste his time with this junk. I guess you could try"
  - "Will usually knows about this weird-o, obscure stuff. Or try"
  - "Ben S. usually knows about this weird-o, obscure stuff. Or try"
