base: &base
  adapter: sqlite3
  host: localhost
  username: br_db_user
  password: br_db_pass
  encoding: utf8
  reconnect: true
  collation: utf8_general_ci

development:
  database: reg_development.sqlite3
  <<: *base

test:
  database: reg_test<%= ENV['TEST_ENV_NUMBER'] %>.sqlite3
  <<: *base

production:
  database: /var/www/reg/shared/reg_production.sqlite3
  <<: *base
